[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ArchCentral"
description = "An Arch Linux control center utility built with PySide6"
version = "0.0.1"
readme = "README.md"

dependencies = [
    "PySide6",
]

[project.scripts]
archcentral = "archcentral.__main__:main"
