[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ArchCentral"
description = "An Arch Linux control center utility built with PySide6"
version = "2026-1"
readme = "README.md"

dependencies = [
    "PySide6",
    "pyqtgraph",
    "psutil",
    "pyalpm",
    "pydbus",
    "PyGObject"
]

[project.scripts]
archcentral = "archcentral.__main__:main"

[tool.setuptools]
packages = ["archcentral"]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-qt"
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = ["."]
testpaths = ["archcentral-tests"]
